[project]
name = "chatbot-mcp-enabled"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.75.0",
    "boto3>=1.42.18",
    "bs4>=0.0.2",
    "fastapi>=0.128.0",
    "ipykernel>=7.1.0",
    "mcp>=1.25.0",
    "mcp-client>=0.0.0",
    "python-dotenv>=1.2.1",
]
